### ISSUE TITLE
Basic checklist at this point

### ISSUE THREAD

**Issue by stahnma** [stahnma/rb-tumble#1]
- [ ] Problem validating kickstarter links like https://www.kickstarter.com/projects/shiftmoonwalkers/moonwalkers-the-worlds-fastest-shoes/ (also a crocs link, something with ja6)
- [ ] Link https://i.imgur.com/tG6HvX2.png validation
- [x] youtube links (as opposed to youtu.be links) are not doing playback rendering properly.
- [x] youtube shorts also don't work.
- [ ] last week's hot shit shouldn't overflow the div for things like twitter links
- [x] Don't post zoom links by default
- [ ] Allow for intentional no posting with a `!` or something
- [ ] Missing dates on the main page. 

# Futures
- [ ] make a stats page with things like top posters, top links, top domains, etc

**Comment by stahnma** [comment]
Old n busted

**Comment by stahnma** [comment]
Old n busted

**Comment by stahnma** [comment]
Acitivty

**Comment by stahnma** [comment]
Old n busted
